services:

  gateway:
    image: kong:latest
    container_name: gateway
    ports:
      - "8000:8000"
      - "8002:8002" # Strictly for admin access, this is not secure.
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8002
    networks:
      - kong-network
    volumes:
      - ./gateway/kong.yml:/kong/kong.yml:ro

  redis:
    image: redis:7
    container_name: redis
    command: >
      redis-server
      --maxmemory 500mb
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
    ports:
      - "6379:6379"
    networks:
      - kong-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    ports:
      - "15672:15672" # Management port
    environment:
      - RABBITMQ_LOGS=rabbit.log
    networks:
      - kong-network
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  elasticsearch:
    image: elasticsearch:9.0.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=changeme
    #  - path.repo=/mnt/backups
    ports:
      - "9200:9200"
    networks:
      - kong-network
    volumes:
      - es-data:/usr/share/elasticsearch/data
    #  - ./backups:/mnt/backups
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      # Correct this
      test: ["CMD-SHELL", "curl -f -u elastic:changeme http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kong-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - kong-network

  fluentd:
    container_name: fluentd
    build:
      dockerfile: ./fluentd/Dockerfile
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    networks:
      - kong-network

  kibana:
    image: kibana:9.0.4
    environment:
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL215LWtpYmFuYS10b2tlbjowQnFLbjZlbVNDTzBrS3hvQ2pQT3V3
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - kong-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    networks:
      - kong-network
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: minio_root_password
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

    #restart: unless-stopped

  database:
    image: postgres:17.5-alpine
    container_name: database
    env_file:
      - ./util/database.test.env
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kong-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d users" ]
      interval: 10s
      timeout: 5s
      retries: 5

  users:
    env_file:
      - users/prod.env
      - util/database.test.env
    build:
      dockerfile: ./users/Dockerfile
    container_name: users
    networks:
      - kong-network
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_healthy

  scraper:
    env_file:
      - scraper/prod.env
      - util/rabbit_mq.test.env
    build:
      dockerfile: ./scraper/Dockerfile
    container_name: scraper
    networks:
      - kong-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  analyzer:
    env_file:
      - analyzer/test.env
      - util/rabbit_mq.test.env
    build:
      dockerfile: ./analyzer/Dockerfile
    container_name: analyzer
    networks:
      - kong-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]

  query-processor:
    env_file:
      - query_processor/test.env
      - util/rabbit_mq.test.env
    build:
      dockerfile: ./query_processor/Dockerfile
    container_name: query-processor
    networks:
      - kong-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  kong-network:
    driver: bridge

volumes:
  grafana-data:
  es-data:
  #pgdata: