{
 "title": "Query processor",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Emociones de Ekman ",
   "type": "bargauge",
   "description": "Cantidad de emociones de Ekman resultantes del mapeo.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mapping_results_total", "legendFormat": "{{value}}" }
   ]
  },
  {
   "title": "Resultados de analisis emocional",
   "type": "timeseries",
   "description": "Cuantifica cantidad de analisis exitosos (completos) o que resultaron en timeout.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "query_results_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Pedidos de analisis emocional",
   "type": "timeseries",
   "description": "Cuantifica todos los pedidos de analisis entrantes al sistema.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "analysis_requests_total", "legendFormat": "cantidad de pedidos" }
   ]
  },
  {
   "title": "Tiempo de espera por analisis",
   "type": "timeseries",
   "description": "Cuantifica tiempo de espera en la cola hasta que se recibe el resultado del analisis emocional.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expression": "$A/$C", "type": "math" }
   ]
  }
 ]
}