{
 "title": "Users",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Duracion de consultas a BDD",
   "type": "gauge",
   "description": "Tiempo de duracion de consultas en base de datos",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "A", "reducer": "mean", "type": "reduce" }
   ]
  },
  {
   "title": "Intentos de logeo",
   "type": "timeseries",
   "description": "Cuantifica intentos de logeo al sistema, exitosos y no exitosos.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    { "expr": "login_attempts_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Borrado de usuarios",
   "type": "timeseries",
   "description": "Cuantifica intentos de borrado de usuarios, tanto exitosos como no exitosos.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "targets": [
    { "expr": "user_deletions_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Registros de nuevos usuarios",
   "type": "timeseries",
   "description": "Cuantifica exitos y errores en los registros de nuevos usuarios.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "targets": [
    { "expr": "user_registrations_total", "legendFormat": "{{status}}" }
   ]
  }
 ]
}