name: Postman integration testing

on:
  pull_request:
    branches:
      - develop

jobs:
  integration-tests:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1.2.0

    - name: Set up all containers for testing
      run: docker compose -f docker-compose.yml up -d
      working-directory: .

    - name: Install Postman CLI
      run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - name: Authenticate Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

    - name: Run integration tests
      run: postman collection run ${{ secrets.POSTMAN_COLLECTION_ID }}