name: Postman integration testing

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1.2.0

    - name: Set up all containers for testing
      run: docker compose -d -f docker-compose.yml -f docker-compose.prod.yml up
      working-directory: .

    - name: Install Postman CLI
      run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    - name: Authenticate Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

    - name: Run integration tests
      run: postman collection run ${{ secrets.POSTMAN_COLLECTION_ID }}